---

path:
    logs: "logs"
    log_config: "configs/logging.yml"
    server: "//cfs2e.nist.gov/642/internal/3D Printing Lab/Shopbot/videos/"
    fig: "C:/Users/lmf1/OneDriveNIST/NIST/data/shopbot/results/singleLines"
    rheTable: "C:/Users/lmf1/OneDriveNIST/NIST/data/material properties/rheology/summaries/vidRhe.xlsx"
    sigmaTable: "C:/Users/lmf1/OneDriveNIST/NIST/data/material properties/surface tension/litsurfacetension.xlsx"
    densityTable: "C:/Users/lmf1/OneDriveNIST/NIST/data/material properties/vidDensities.xlsx"
    pCalibFolder: "C:/Users/lmf1/OneDriveNIST/NIST/data/material properties/flow rates"
    openFoamFolder: "C:/Users/lmf1/OneDriveNIST/NIST/data/openfoam/summaries"
const:
    di: 0.603
    do: 0.907
    vink: 5
    vsup: 5
    pxpmm: 139 # px/mm

    